#!/bin/bash

port=4567

start_server() {
  pushd actionview > /dev/null
  mkdir -p log
  bundle exec ruby test/ujs/server.rb > log/test.log 2>&1 &
  popd> /dev/null
}

run_tests() {
  pushd actionview && npm run lint && popd && phantomjs ci/runner.js http://localhost:$port/
}

server_started() {
  lsof -i :${1?} >/dev/null
}

timestamp() {
  date +%s
}

wait_for_server() {
  timeout=$(( `timestamp` + $1 ))
  while true; do
    if server_started "$2"; then
      break
    elif [ `timestamp` -gt "$timeout" ]; then
      echo "timed out after $1 seconds" >&2
      exit 1
    fi
  done
}

start_server
server_pid=$!
wait_for_server 5 $port
run_tests
result=$?
kill $server_pid
exit $result
